Calculadora/Controllers/HistorialController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using System.Diagnostics;
using Calculadora.Data;
using Calculadora.Models;
using Calculadora.Intermediario;
using Calculadora.Repository;


namespace Calculadora.Controllers
{
    public class HistorialController : Controller
    {

        private ICalculadoraRepository _repository;
        private IWebHostEnvironment _environment;

        public HistorialController(ICalculadoraRepository repository, IWebHostEnvironment environment)
        {
            _repository = repository;
            _environment = environment;
        }

        public IActionResult VerOperaciones()
        {
            return View("VerOperaciones",_repository.GetOperationById());
        }

        public IActionResult Delete(int id)
        {
            _repository.DeleteOperation(id);
            return RedirectToAction("VerOperaciones","/Historial");
        }

        public void DeleteAll(int id)
        {
            _repository.DeleteOperation(id);
        }
       
    }
}

Calculadora/Controllers/UsuariosLRController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using System.Diagnostics;
using Calculadora.Data;
using Calculadora.Models;
using Calculadora.Intermediario;
using Calculadora.Repository;


namespace Calculadora.Controllers
{
    public class UsuariosLRController : Controller
    {

        private ICalculadoraRepository _repository;

        private IWebHostEnvironment _environment;

        public UsuariosLRController(ICalculadoraRepository context, IWebHostEnvironment environment)
        {
            _repository = context;
            _environment = environment;
        }

        public IActionResult AddUser(Usuario user)
        {
            try
            {
                if (Estatico.IdConectado != 0 && user == null)
                {
                    return Redirect("WatchUserAccount");
                }
                else
                {

                    _repository.AddUserWithPasswd(user);
                    Estatico.IdConectado = _repository.GetIdByUser(user);
                    Estatico.UserName = user.NombreUsuario;
                    return Redirect("/Home/CalculadoraCon");

                }


            }
            catch
            {
                Estatico.IdConectado = 0;
                Estatico.UserName = "";
                return RedirectToAction("Register", new { mensaje = "NOADD" });
            }
        }




        public IActionResult Login(Usuario user)
        {
            try
            {
                if (user.Email != null)
                {

                    if (!_repository.LoginUserPasswd(user))
                    {
                        if (!_repository.LoginName(user.NombreUsuario))
                        {
                            Estatico.IdConectado = 0;
                            Estatico.UserName = "";
                            return View("Login", "error");
                        }
                        else
                        {
                            Estatico.IdConectado = 0;
                            Estatico.UserName = "";
                            return View("Login", "noLogin");
                        }
                    }
                    else
                    {
                        Estatico.IdConectado = _repository.GetIdByUser(user);
                        Estatico.UserName = _repository.GetUserByID().NombreUsuario;
                        return Redirect("/Home/CalculadoraCon");
                    }
                }
                else
                {
                    if (Estatico.IdConectado != 0)
                    {
                        return Redirect("WatchUserAccount");
                    }
                    else
                    {
                        Estatico.IdConectado = 0;
                        Estatico.UserName = "";
                        return View("Login", "error");
                    }
                }

            }
            catch (Exception)
            {

                Estatico.IdConectado = 0;
                Estatico.UserName = "";
                return View("Login", "error");

            }

        }

        public IActionResult Register(string? mensaje)
        {
            if (Estatico.IdConectado == 0)
            {
                return View(mensaje);
            }
            else
            {
                return Redirect("WatchUserAccount");

            }
        }

        public IActionResult Conectarse()
        {
            if (Estatico.IdConectado == 0)
            {
                return View("Login");
            }
            else
            {
                return View("WatchUserAccount");
            }

        }
        public IActionResult WatchUserAccount()
        {
            return View(_repository.GetUserByID());
        }
        public IActionResult Editar()
        {
            return View("Editar", _repository.GetUserByID());
        }
        public IActionResult DeleteConfirm()
        {
            _repository.DeleteUser();
            Estatico.UserName = "";
            Estatico.IdConectado = 0;
            return RedirectToAction("Index","Home");
        }
        public IActionResult ConfirmarEdicion(Usuario user)
        {
            Usuario id = _repository.GetUserByID();
            id.NombreUsuario = user.NombreUsuario;
            id.Email = user.Email;
            id.Password = user.Password;
            _repository.EditarUsuario(id);
            return Redirect("WatchUserAccount");

        }

    }
}

Calculadora/Views/Historial/VerOperaciones.cshtml
@{
    IEnumerable<Operaciones> listaOperaciones = Model;
    ViewData["Title"] = "Página de Operaciones";
    int contador = 0;
}

<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        text-align: left;
        padding: 8px;
    }

    th {
        background-color: #003366;
        color: white;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    tr:hover {
        background-color: #ddd;
    }

    #selectAll {
        margin-right: 5px;
    }

    .eliminar-button {
        background-color: #dc3545;
        color: white;
        border: none;
        padding: 8px 16px;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

        .eliminar-button:hover {
            background-color: #c82333;
        }

</style>

<table>
    @if (Estatico.IdConectado != 0)
    {
        @if (listaOperaciones.Count() == 0)
        {
            <thead>
                <tr>
                    <td colspan="5">No hay operaciones registradas. Por favor, realice algunas operaciones para verlas aquí.</td>


                </tr>
                <a asp-controller="Home" asp-action="CalculadoraCon" class="btn btn-primary">Ir a la calculadora</a>
            </thead>
        }
        else
        {
            <thead>
                <tr>
                    <th>Número</th>
                    <th>Expresión Matemática</th>
                    <th>Resultado</th>
                    <th>Fecha y Hora</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in listaOperaciones)
                {
                    <tr>
                        <td>@(contador + 1)</td>
                        <td>@item.ExpresionMatematica</td>
                        <td>@item.Resultado</td>
                        <td>@item.fechaHora</td>
                        <td style="display: flex; align-content: center;justify-content: space-evenly;">
                            <form asp-area="" asp-controller="Historial" asp-action="Delete" asp-route-id="@item.Id" method="post">
                                <button type="submit" class="eliminar-button">Eliminar</button>
                            </form>

                            @*<a asp-controller="Home" asp-action="DarValor" asp-route-id="@item.Id" class="eliminar-button" style="text-decoration:none; background-color:forestgreen;">USAR</a>*@
                        </td>
                    </tr>
                    contador++;
                }
            </tbody>

        }

    }
    else
    {
        <thead>
            <tr>
                <td colspan="5">Si quiere ver sus operaciones debe primero Loggearse.</td>
            </tr>
            <tr>
                <form asp-area="" asp-controller="UsuariosLR" asp-action="Conectarse" method="post">
                    <button type="submit" class="eliminar-button">Log in</button>
                </form>
                 
            </tr>
        </thead>
    }
</table>